exports.birds = exports.birds = [
    {
      name: "Birdie",
      species: "Parrot",
      breed: "African Grey",
      sex: "M",
      breeder: "John Doe",
      owner: "Jane Smith",
      cockParent: "Cocky",
      henParent: "Henrietta",
      hatchBatch: "HB123",
      sold: (new Date("2021-10-17")).toISOString(),
      deceased: (new Date("2021-10-19")).toISOString(),
      hatch_date: (new Date("2023-01-15")).toISOString(),
      location: "Aviary 1",
      color: "Grey",
      healthEvents: ["Vaccination", "Check-up"],
      showPlacing: "1st",
      weights: 1
    },
    {
      name: "Feathers",
      species: "Parrot",
      breed: "Cockatiel",
      sex: "F",
      breeder: "Alice Johnson",
      owner: "Bob Miller",
      cockParent: "Captain",
      henParent: "Harmony",
      hatchBatch: "HB456",
      sold: null,
      deceased: null,
      hatch_date: (new Date("2023-02-20")).toISOString(),
      location: "Aviary 2",
      color: "Yellow",
      healthEvents: ["Check-up"],
      showPlacing: "2nd",
      weights: 2
    },
    {
      name: "Squawks",
      species: "Parrot",
      breed: "Amazon",
      sex: "M",
      breeder: "Eva Brown",
      owner: "David Smith",
      cockParent: "Thunder",
      henParent: "Rainbow",
      hatchBatch: "HB789",
      sold: (new Date("2023-03-05")).toISOString(),
      deceased: null,
      hatch_date: (new Date("2023-05-10")).toISOString(),
      location: "Aviary 3",
      color: "Green",
      healthEvents: ["Vaccination", "Check-up"],
      showPlacing: "3rd",
      weights: 3
    },
    {
      name: "Whisper",
      species: "Songbird",
      breed: "Nightingale",
      sex: "F",
      breeder: "Frank Williams",
      owner: "Grace Davis",
      cockParent: "Solo",
      henParent: "Melody",
      hatchBatch: "HB987",
      sold: null,
      deceased: null,
      hatch_date: (new Date("2023-06-15")).toISOString(),
      location: "Aviary 4",
      color: "Brown",
      healthEvents: ["Check-up"],
      showPlacing: "1st",
      weights: 4
    },
    {
      name: "Blaze",
      species: "Bird of Prey",
      breed: "Hawk",
      sex: "M",
      breeder: "Helen Thompson",
      owner: "Ian Robinson",
      cockParent: "Phoenix",
      henParent: "Firefly",
      hatchBatch: "HB654",
      sold: null,
      deceased: (new Date("2023-08-02")).toISOString(),
      hatch_date: (new Date("2023-04-05")).toISOString(),
      location: "Aviary 5",
      color: "Red",
      healthEvents: ["Injury treatment", "Check-up"],
      showPlacing: "2nd",
      weights: 5
    }
  ];
  